const actionTypes = {
    /* PRODUCTS ACTIONS START */
    PRODUCT_LIST_REQUEST : 'PRODUCT_LIST_REQUEST',
    PRODUCT_LIST_SUCCESS : 'PRODUCT_LIST_SUCCESS',
    PRODUCT_LIST_FAIL : 'PRODUCT_LIST_FAIL',
    /* PRODUCT ACTIONS END */ 

    /* PRODUCT ACTIONS START */
    PRODUCT_REQUEST : 'PRODUCT_REQUEST',
    PRODUCT_SUCCESS : 'PRODUCT_SUCCESS',
    PRODUCT_FAIL : 'PRODUCT_FAIL',
    /* PRODUCT ACTIONS END */ 
};


export default actionTypes;