const actionTypes = {
    /* PRODUCTS ACTIONS START */
    PRODUCT_LIST_REQUEST : 'PRODUCT_LIST_REQUEST',
    PRODUCT_LIST_SUCCESS : 'PRODUCT_LIST_SUCCESS',
    PRODUCT_LIST_FAIL : 'PRODUCT_LIST_FAIL',
    /* PRODUCT ACTIONS END */

    /* LOGIN USUARIO */
    AUTH_REQUEST : 'AUTH_REQUEST',
    AUTH_RECEIVE : 'AUTH_RECEIVE',
    AUTH_ERROR : 'AUTH_ERROR', 
    AUTH_LOGOUT: 'AUTH_LOGOUT',

    /* LISTA USUARIO */
    USER_LIST_REQUEST : 'USER_LIST_REQUEST',
    USER_LIST_SUCCESS : 'USER_LIST_SUCCESS',
    USER_LIST_FAIL : 'USER_LIST_FAIL',
    USER_LIST_RESET :'USER_LIST_RESET',

    USER_LOGIN_LOGOUT: 'USER_LOGIN_LOGOUT',
    USER_DETAILS_RESET: 'USER_DETAILS_RESET',
    ORDER_LIST_MY_RESET: 'ORDER_LIST_MY_RESET',
    USER_LIST_RESET:'USER_LIST_RESET',

    /* REGISTRO USUARIO */
    REGISTER_REQUEST : 'REGISTER_REQUEST',
    REGISTER_RECEIVE : 'REGISTER_RECEIVE',
    REGISTER_ERROR : 'REGISTER_ERROR',
      
    /*un producto */
    PRODUCT_REQUEST : 'PRODUCT_REQUEST',
    PRODUCT_SUCCESS : 'PRODUCT_SUCCESS',
    PRODUCT_FAIL : 'PRODUCT_FAIL',

    CREATE_PRODUCT_REQUEST:'CREATE_PRODUCT_REQUEST',
    CREATE_PRODUCT_SUCCESS:'CREATE_PRODUCT_SUCCESS',
    CREATE_PRODUCT_FAIL:'CREATE_PRODUCT_FAIL',

    UPDATE_PRODUCT_REQUEST:'UPDATE_PRODUCT_REQUEST',
    UPDATE_PRODUCT_SUCCESS:'UPDATE_PRODUCT_SUCCESS',
    UPDATE_PRODUCT_FAIL:'UPDATE_PRODUCT_FAIL',

    DELETE_PRODUCT_REQUEST:'DELETE_PRODUCT_REQUEST',
    DELETE_PRODUCT_SUCCESS:'DELETE_PRODUCT_SUCCESS',
    DELETE_PRODUCT_FAIL:'DELETE_PRODUCT_FAIL',

    PRODUCT_CREATE_REVIEW_REQUEST: 'PRODUCT_CREATE_REVIEW_REQUEST',
    PRODUCT_CREATE_REVIEW_SUCCESS: 'PRODUCT_CREATE_REVIEW_SUCCESS',
    PRODUCT_CREATE_REVIEW_FAIL: 'PRODUCT_CREATE_REVIEW_FAIL',
    PRODUCT_CREATE_REVIEW_RESET: 'PRODUCT_CREATE_REVIEW_RESET',

};


export default actionTypes;