const actionTypes = {
    /* PRODUCTS ACTIONS START */
    PRODUCT_LIST_REQUEST : 'PRODUCT_LIST_REQUEST',
    PRODUCT_LIST_SUCCESS : 'PRODUCT_LIST_SUCCESS',
    PRODUCT_LIST_FAIL : 'PRODUCT_LIST_FAIL',
    /* PRODUCT ACTIONS END */ 

    /* PRODUCT ACTIONS START */
    PRODUCT_REQUEST : 'PRODUCT_REQUEST',
    PRODUCT_SUCCESS : 'PRODUCT_SUCCESS',
    PRODUCT_FAIL : 'PRODUCT_FAIL',
    /* PRODUCT ACTIONS END */ 
    
    /* PRODUCT ACTIONS START */
    PRODUCT_CREATE_REVIEW_REQUEST: 'PRODUCT_CREATE_REVIEW_REQUEST',
    PRODUCT_CREATE_REVIEW_SUCCESS: 'PRODUCT_CREATE_REVIEW_SUCCESS',
    PRODUCT_CREATE_REVIEW_FAIL: 'PRODUCT_CREATE_REVIEW_FAIL',
    PRODUCT_CREATE_REVIEW_RESET: 'PRODUCT_CREATE_REVIEW_RESET',
    /* PRODUCT ACTIONS END */ 
};


export default actionTypes;